### ISSUE TITLE
Filter Data when user clicks on the line

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#21] opened 2017-01-30 12:05 UTC
![image](https://cloud.githubusercontent.com/assets/12292333/22422458/be5c5c04-e6ec-11e6-96f3-1913d3b0755c.png)
Filter Data excluding Barbados

**Comment by mstreit** [comment] 2017-01-30 14:24
Duplicate of #13?

**Closed** 2017-02-15 16:49 UTC
Labels: dropped idea
