### ISSUE TITLE
Let user change column width interactively

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#58] opened 2017-02-07 14:40 UTC
The user should be able to resize the width of the column by some icon on the header or by dragging left or right as in lineup.

**Comment by mstreit** [comment] 2017-03-06 10:33
@mijar, are you working on this or can @thinkh take over the issue?

**Comment by mstreit** [comment] 2017-03-06 15:54
Is #106 a duplicate of this issue?

**Comment by thinkh** [comment] 2017-03-06 15:57
Yes. The #106 seems to be more specific, so I would use that as reference and close this.

**Closed by thinkh** 2017-03-06 15:57 UTC
