### ISSUE TITLE
Wrong x-scaling factor for multiform visualizations 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/mothertable#198] opened 2017-03-07 20:58 UTC
### Steps to reproduce

1. Checkout https://github.com/Caleydo/mothertable/pull/197
2. Add multiple columns until they start to shrink or resize the window

### Observed behavior

![taggle_space-filling-columns](https://cloud.githubusercontent.com/assets/5851088/23677650/46e31904-0381-11e7-84b6-5250927876cf.gif)

* The visualizations does not scale correctly in x-direction
* For the y-direction it's working correctly
* You can see in the animation above that the header and matrices are scaled correctly
* Only vectors(?) are not correct(?)

### Expected behavior
* The visualization should adapt to the new given width properly

**Comment by mstreit** [comment] 2017-03-08 09:40
@katush, can you please look at this problem soon? I would like to show a quick demo in the BI project meeting tomorrow.

**Comment by katush** [comment] 2017-03-08 23:49
It was caused by "height-only" restriction on scaling. Sorry this simple solution took so long, I was quite puzzled by disappearing scale factors. 😃 Should be fixed by https://github.com/phovea/phovea_vis/pull/36

**Comment by mstreit** [comment] 2017-03-09 07:16
Works, thanks!

**Closed by mstreit** 2017-03-09 07:16 UTC
Labels: bug, high priority
