### ISSUE TITLE
Preview in the table view of the ratio of how much data we lose by filtering something out on mouse hover in filter view

### ISSUE THREAD

**Issue by mijar** [Caleydo/mothertable#71] opened 2017-02-07 17:52 UTC
Do we still count with this one?

**Comment by mstreit** [comment] 2017-02-13 13:18
Would be nice, but has a low priority for now.

**Comment by mstreit** [comment] 2017-03-07 15:03
Duplicate of #81. I'm closing this one.

**Closed by mstreit** 2017-03-07 15:03 UTC
Labels: low priority
